# Generated by Django 5.0.1 on 2024-09-10 14:31

import app_fhir.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fhir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(default='2000-01-01', verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='genre',
            field=models.CharField(choices=[('Female', 'Femme'), ('Male', 'Homme')], default='Male', max_length=10, verbose_name=app_fhir.models.Patient.Genre),
        ),
    ]
